// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/almostinf/glow-reminder/pkg/glow_reminder/models"
)

// NewGlowReminderParams creates a new GlowReminderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGlowReminderParams() *GlowReminderParams {
	return &GlowReminderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGlowReminderParamsWithTimeout creates a new GlowReminderParams object
// with the ability to set a timeout on a request.
func NewGlowReminderParamsWithTimeout(timeout time.Duration) *GlowReminderParams {
	return &GlowReminderParams{
		timeout: timeout,
	}
}

// NewGlowReminderParamsWithContext creates a new GlowReminderParams object
// with the ability to set a context for a request.
func NewGlowReminderParamsWithContext(ctx context.Context) *GlowReminderParams {
	return &GlowReminderParams{
		Context: ctx,
	}
}

// NewGlowReminderParamsWithHTTPClient creates a new GlowReminderParams object
// with the ability to set a custom HTTPClient for a request.
func NewGlowReminderParamsWithHTTPClient(client *http.Client) *GlowReminderParams {
	return &GlowReminderParams{
		HTTPClient: client,
	}
}

/*
GlowReminderParams contains all the parameters to send to the API endpoint

	for the glow reminder operation.

	Typically these are written to a http.Request.
*/
type GlowReminderParams struct {

	/* Body.

	   Glow Reminder object
	*/
	Body *models.GlowReminder

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the glow reminder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GlowReminderParams) WithDefaults() *GlowReminderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the glow reminder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GlowReminderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the glow reminder params
func (o *GlowReminderParams) WithTimeout(timeout time.Duration) *GlowReminderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the glow reminder params
func (o *GlowReminderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the glow reminder params
func (o *GlowReminderParams) WithContext(ctx context.Context) *GlowReminderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the glow reminder params
func (o *GlowReminderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the glow reminder params
func (o *GlowReminderParams) WithHTTPClient(client *http.Client) *GlowReminderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the glow reminder params
func (o *GlowReminderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the glow reminder params
func (o *GlowReminderParams) WithBody(body *models.GlowReminder) *GlowReminderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the glow reminder params
func (o *GlowReminderParams) SetBody(body *models.GlowReminder) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GlowReminderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
