// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GlowReminderReader is a Reader for the GlowReminder structure.
type GlowReminderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GlowReminderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGlowReminderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGlowReminderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /glow_reminder] glow_reminder", response, response.Code())
	}
}

// NewGlowReminderOK creates a GlowReminderOK with default headers values
func NewGlowReminderOK() *GlowReminderOK {
	return &GlowReminderOK{}
}

/*
GlowReminderOK describes a response with status code 200, with default header values.

successful operation
*/
type GlowReminderOK struct {
}

// IsSuccess returns true when this glow reminder o k response has a 2xx status code
func (o *GlowReminderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this glow reminder o k response has a 3xx status code
func (o *GlowReminderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this glow reminder o k response has a 4xx status code
func (o *GlowReminderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this glow reminder o k response has a 5xx status code
func (o *GlowReminderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this glow reminder o k response a status code equal to that given
func (o *GlowReminderOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the glow reminder o k response
func (o *GlowReminderOK) Code() int {
	return 200
}

func (o *GlowReminderOK) Error() string {
	return fmt.Sprintf("[POST /glow_reminder][%d] glowReminderOK", 200)
}

func (o *GlowReminderOK) String() string {
	return fmt.Sprintf("[POST /glow_reminder][%d] glowReminderOK", 200)
}

func (o *GlowReminderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGlowReminderInternalServerError creates a GlowReminderInternalServerError with default headers values
func NewGlowReminderInternalServerError() *GlowReminderInternalServerError {
	return &GlowReminderInternalServerError{}
}

/*
GlowReminderInternalServerError describes a response with status code 500, with default header values.

Internal Error
*/
type GlowReminderInternalServerError struct {
}

// IsSuccess returns true when this glow reminder internal server error response has a 2xx status code
func (o *GlowReminderInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this glow reminder internal server error response has a 3xx status code
func (o *GlowReminderInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this glow reminder internal server error response has a 4xx status code
func (o *GlowReminderInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this glow reminder internal server error response has a 5xx status code
func (o *GlowReminderInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this glow reminder internal server error response a status code equal to that given
func (o *GlowReminderInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the glow reminder internal server error response
func (o *GlowReminderInternalServerError) Code() int {
	return 500
}

func (o *GlowReminderInternalServerError) Error() string {
	return fmt.Sprintf("[POST /glow_reminder][%d] glowReminderInternalServerError", 500)
}

func (o *GlowReminderInternalServerError) String() string {
	return fmt.Sprintf("[POST /glow_reminder][%d] glowReminderInternalServerError", 500)
}

func (o *GlowReminderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
